/* eslint-disable react/react-in-jsx-scope */
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../styles/globals.css'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.variable} font-sans`}>{children}</body>
    </html>
  )
}
